website/static/css/custom.css

Show logo on small devices

---

website/crowdin.yaml
website/package.json

This helps simplifying the Crowdin commands in the website's `package.json` while keeping the project's root cleaner.

Move Crowdin config to website directory

---

packages/warriorjs-cli/src/ui/printBoard.js
packages/warriorjs-cli/src/ui/printBoard.test.js
packages/warriorjs-cli/src/ui/printWarriorStatus.js
packages/warriorjs-cli/src/ui/printWarriorStatus.test.js
packages/warriorjs-core/src/Warrior.js

Allows users to see how their score changes turn by turn.
Change health color from red to bright red.

Add warrior score next to health in play log (#48)

---

packages/warriorjs-cli/src/Game.test.js
packages/warriorjs-cli/src/Profile.test.js

Previously, running tests on a non-posix machine (eg. Windows) would
cause several to fail. The cause of the failure was file path comparison.
The expected values were written as posix style file paths (eg. a/b/c.txt)
while the actual values were returning windows style file paths (eg. a\\b\\c.txt).
The solution to this was to use node's built in path module to normalize
the paths for each system (https://nodejs.org/api/path.html#path_path_normalize_path).
closes #76

Fix path normalization in tests

---

packages/warriorjs-abilities/README.md
packages/warriorjs-abilities/src/rescue.js
packages/warriorjs-abilities/src/rescue.test.js

Allow the rescue ability to award the number
of points assigned to the unit being rescued.

Rescue ability awarts unit's reward (#64)

---

packages/warriorjs-core/src/LevelLoader.js
packages/warriorjs-core/src/Unit.js
packages/warriorjs-units/src/Captive.js
packages/warriorjs-units/src/Captive.test.js

This was necessary to properly close #64.

Add reward to Captive unit

---

packages/warriorjs-core/src/Unit.js
packages/warriorjs-core/src/Unit.test.js

When killing a friendly unit, subtracts its reward points.
To implement this, the new method `losePoints` has been added to the `Unit` class, which will substract the given points from the unit ~(but doesn't decrement its score under zero)~.
Closes #62

Subtract reward points when killing a friendly unit

---

packages/warriorjs-abilities/README.md
packages/warriorjs-abilities/src/index.js
packages/warriorjs-abilities/src/think.js
packages/warriorjs-abilities/src/think.test.js
packages/warriorjs-tower-beginner/src/index.js
packages/warriorjs-tower-intermediate/src/index.js

Think is a sense that allows the player to log arbitrary strings to the play log **before performing the action of the turn**.

Add think ability

---

packages/warriorjs-cli/src/ui/printWarriorStatus.js
packages/warriorjs-cli/src/ui/printWarriorStatus.test.js

Hello!
This change should fix the diamond symbol on Windows' CMD.
I used the is-windows util to check the user env and in case that returns true, I use the Black Diamond Suit (as suggested on the issue), otherwise I keep the black medium diamond symbol.
I hope that helps.
Fixes #112

Fixed diamond symbol on windows CMD

---

packages/warriorjs-abilities/src/attack.js
packages/warriorjs-abilities/src/attack.test.js
packages/warriorjs-abilities/src/bind.js
packages/warriorjs-abilities/src/bind.test.js
packages/warriorjs-abilities/src/detonate.js
packages/warriorjs-abilities/src/detonate.test.js
packages/warriorjs-abilities/src/pivot.js
packages/warriorjs-abilities/src/pivot.test.js
packages/warriorjs-abilities/src/rescue.js
packages/warriorjs-abilities/src/rescue.test.js
packages/warriorjs-abilities/src/rest.js
packages/warriorjs-abilities/src/rest.test.js
packages/warriorjs-abilities/src/shoot.js
packages/warriorjs-abilities/src/shoot.test.js
packages/warriorjs-abilities/src/think.js
packages/warriorjs-abilities/src/think.test.js
packages/warriorjs-abilities/src/walk.js
packages/warriorjs-abilities/src/walk.test.js
packages/warriorjs-core/src/Level.test.js
packages/warriorjs-core/src/Unit.js
packages/warriorjs-core/src/Unit.test.js
packages/warriorjs-core/src/Warrior.js
packages/warriorjs-core/src/Warrior.test.js
packages/warriorjs-core/src/getLevel.test.js
packages/warriorjs-core/src/runLevel.test.js
packages/warriorjs-effects/src/ticking.js
packages/warriorjs-effects/src/ticking.test.js

Rename `unit.say()` to the more appropriate `unit.log()`.

Rename say to log

---

packages/warriorjs-cli/src/Profile.js
packages/warriorjs-cli/src/Profile.test.js

Hello!
There were some problems while rebasing the previous branch.
This one follows the same approach, checking for the Player.js file as requested on the issue.
Tests are already written for the new function.
Hope it helps.

Improve profile directory detection

---

packages/warriorjs-abilities/src/rescue.js
packages/warriorjs-abilities/src/rescue.test.js
packages/warriorjs-core/src/Unit.js
packages/warriorjs-core/src/Unit.test.js

Move release logic (unbinding and scoring) from the rescue ability to the core.

Add unit.release() method

---

docs/js-tips.md
docs/space-api.md
docs/unit-api.md
packages/warriorjs-abilities/src/feel.js
packages/warriorjs-abilities/src/feel.test.js
packages/warriorjs-abilities/src/listen.js
packages/warriorjs-abilities/src/listen.test.js
packages/warriorjs-abilities/src/look.js
packages/warriorjs-abilities/src/look.test.js
packages/warriorjs-core/src/Floor.test.js
packages/warriorjs-core/src/Level.js
packages/warriorjs-core/src/LevelLoader.js
packages/warriorjs-core/src/Position.js
packages/warriorjs-core/src/Position.test.js
packages/warriorjs-core/src/Space.js
packages/warriorjs-core/src/Space.test.js
packages/warriorjs-core/src/Unit.js
packages/warriorjs-core/src/Unit.test.js
packages/warriorjs-core/src/getLevel.test.js
packages/warriorjs-core/src/runLevel.test.js
packages/warriorjs-tower-beginner/src/index.js
packages/warriorjs-tower-intermediate/src/index.js
packages/warriorjs-units/src/Archer.js
packages/warriorjs-units/src/Archer.test.js
packages/warriorjs-units/src/Captive.js
packages/warriorjs-units/src/Captive.test.js
packages/warriorjs-units/src/Sludge.js
packages/warriorjs-units/src/Sludge.test.js
packages/warriorjs-units/src/ThickSludge.test.js
packages/warriorjs-units/src/Wizard.test.js

This PR introduces the entities `SensedSpace` and `SensedUnit`. Whenever a unit gets a space after sensing an area, one or multiple `SensedSpace` will be returned. This new object represents the space as it was perceived by the unit that sensed it. If there was a unit located at the space, that unit will be a `SensedUnit`. Methods called on these sensed entities are now be relative to the unit that sensed them:
* `space.getLocation()`: returns the location of the space as the number of spaces forward and to the right of the unit that sensed it.
* `unit.isEnemy()`: returns whether the unit is considered an enemy by the unit that sensed it.

Sensed space and sensed unit entities

---

packages/warriorjs-cli/package.json
packages/warriorjs-cli/src/Game.js
packages/warriorjs-cli/src/ui/printFloorMap.js
packages/warriorjs-cli/src/ui/printLevel.js
packages/warriorjs-cli/src/ui/printLevel.test.js
packages/warriorjs-cli/src/ui/printLevelDescription.js
packages/warriorjs-cli/src/ui/printLevelDescription.test.js
packages/warriorjs-cli/src/ui/printLevelHeader.js
packages/warriorjs-cli/src/ui/printLevelHeader.test.js
packages/warriorjs-cli/src/ui/printPlay.js
packages/warriorjs-cli/src/ui/printPlay.test.js
packages/warriorjs-cli/src/ui/printRow.js
packages/warriorjs-cli/src/ui/printRow.test.js
packages/warriorjs-cli/src/ui/printSeparator.js
packages/warriorjs-cli/src/ui/printSeparator.test.js
packages/warriorjs-cli/src/ui/printTurnHeader.js
packages/warriorjs-cli/src/ui/printTurnHeader.test.js
yarn.lock

**Before:**
With `--silent`:
**After:**
With `--silent`:

Print level before play (independently)

---

packages/warriorjs-abilities/src/look.js
packages/warriorjs-abilities/src/look.test.js

Enhance "look" ability

---

docs/towers.md
packages/warriorjs-cli/package.json
packages/warriorjs-cli/src/Game.js
packages/warriorjs-cli/src/Game.test.js
packages/warriorjs-cli/src/Profile.js
packages/warriorjs-cli/src/Profile.test.js
packages/warriorjs-cli/src/Tower.js
packages/warriorjs-cli/src/Tower.test.js
packages/warriorjs-cli/src/loadTowers.js
packages/warriorjs-cli/src/loadTowers.test.js
packages/warriorjs-cli/src/utils/getLevelConfig.js
packages/warriorjs-cli/src/utils/getLevelConfig.test.js
packages/warriorjs-cli/src/utils/getTowerId.js
packages/warriorjs-cli/src/utils/getTowerId.test.js
packages/warriorjs-tower-beginner/index.js
packages/warriorjs-tower-beginner/package.json
packages/warriorjs-tower-intermediate/index.js
packages/warriorjs-tower-intermediate/package.json
website/i18n/en.json
website/sidebars.json
yarn.lock

This adds support for community towers, as well as official towers that don't ship with the game. WarriorJS CLI searches for towers (`@warriorjs/tower-*` and `warriorjs-tower-*`) in the nearest parent `node_modules` directory. This should work for both global and local installations of the CLI.
Closes #100 
Fixes #168

Load towers dynamically

---

packages/warriorjs-core/src/loadLevel.js

This allows to omit the `units` array when defining a level without units.

Add units array default value

---

packages/warriorjs-cli/templates/readme/abilities.ejs

Sort actions and senses alphabetically

---

docs/make/defining-abilities.md
docs/make/refactoring.md
packages/warriorjs-abilities/src/pivot.js
packages/warriorjs-abilities/src/walk.js
packages/warriorjs-abilities/src/walk.test.js
packages/warriorjs-core/src/Unit.js
packages/warriorjs-core/src/Unit.test.js

No longer make `unit.log()` calls without message. We used to do that in order to log changes in the unit's position.

Reduce unit.log() calls

---

docs/play/cli-tips.md
packages/warriorjs-cli/src/ui/getUnitStyle.js
packages/warriorjs-cli/src/ui/getUnitStyle.test.js
packages/warriorjs-cli/src/ui/printFloorMap.js
packages/warriorjs-cli/src/ui/printFloorMap.test.js
packages/warriorjs-cli/src/ui/printLogMessage.js
packages/warriorjs-cli/src/ui/printLogMessage.test.js
packages/warriorjs-core/src/Unit.js
packages/warriorjs-core/src/Unit.test.js
packages/warriorjs-core/src/Warrior.js
packages/warriorjs-core/src/Warrior.test.js
packages/warriorjs-core/src/getLevel.test.js
packages/warriorjs-core/src/loadLevel.js
packages/warriorjs-units/src/Archer.js
packages/warriorjs-units/src/Archer.test.js
packages/warriorjs-units/src/Captive.js
packages/warriorjs-units/src/Captive.test.js
packages/warriorjs-units/src/Sludge.js
packages/warriorjs-units/src/Sludge.test.js
packages/warriorjs-units/src/ThickSludge.js
packages/warriorjs-units/src/ThickSludge.test.js
packages/warriorjs-units/src/Warrior.js
packages/warriorjs-units/src/Warrior.test.js
packages/warriorjs-units/src/Wizard.js
packages/warriorjs-units/src/Wizard.test.js

**Before:**
_^ Note how the Archer and the Captive had the same color due to the algorithm that was used to select colors for them automatically._
**After:**
(In the CLI, unit colors are downsampled from RGB to 256 color ANSI for greater uniformity.)

Add RGB color to units

---

package.json
yarn.lock

ESLint v5 is not yet supported by `eslint-config-airbnb`. See https://github.com/airbnb/javascript/issues/1834.

Downgrade ESLint to v4

---

packages/warriorjs-cli/package.json
yarn.lock

In `@warriorjs/cli`.  The new version doesn't bring in a CLI, so install time should be a bit less for the whole package.

Bump `superheroes`.

---

CHANGELOG.md
packages/warriorjs-abilities/src/think.js
packages/warriorjs-abilities/src/think.test.js

Previously, `warrior.think({ foo: 'bar' })` printed `Spartacus thinks [object Object]`. This PR fixes that, plus makes the behavior of `warrior.think()` almost the same as `console.log()`.

Fix think ability
